### ISSUE TITLE
Udemy course error

### ISSUE THREAD

**Issue by mediero** [mikeckennedy/mongodb-quickstart-course#8]
Dear Mike,
i'm doing this course. I'have this issue when i try to update the availability of a cage. Can you help me?
Luis> u
 ****************** Add available date **************** 
You have 2 cages.
 1. Culebra is 1.0 meters.
 2. Boa is 33.0 meters.
Enter cage number: 1
Selected cage Culebra
Enter available date [yyyy-mm-dd]: 2020-10-26
How many days is this block of time? 16
Traceback (most recent call last):
  File "D:/historian_mongo/mongo/snake_bnb/program.py", line 65, in <module>
    main()
  File "D:/historian_mongo/mongo/snake_bnb/program.py", line 17, in main
    program_hosts.run()
  File "D:\historian_mongo\mongo\snake_bnb\src\program_hosts.py", line 31, in run
    s.default(unknown_command)
  File "D:\historian_mongo\mongo\snake_bnb\src\infrastructure\switchlang.py", line 93, in __exit__
    self.__result = func()
  File "D:\historian_mongo\mongo\snake_bnb\src\program_hosts.py", line 158, in update_availability
    svc.add_available_date(
  File "D:\historian_mongo\mongo\snake_bnb\src\data\services\data_service.py", line 64, in add_available_date
    cage.save()
  File "D:\historian_mongo\mongo\venv\lib\site-packages\mongoengine\document.py", line 388, in save
    self.validate(clean=clean)
  File "D:\historian_mongo\mongo\venv\lib\site-packages\mongoengine\base\document.py", line 445, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (Cage:5f90470a942e7bd931bad341) (Invalid embedded document instance provided to an EmbeddedDocumentField: ['bookings'])

Process finished with exit code 1

**Comment by mikeckennedy** [comment]
I can't tell from here but it looks like you're setting the wrong value in bookings.

`cage.bookings.append('THIS THAT IS NOT WHAT IS EXPECTED HERE :)')`
